### ISSUE TITLE
ollama response missing

### ISSUE THREAD

**Issue by j2l** [saltcorn/large-language-model#1]
Hello Tom, 
I tried this one with my local ollama and got `undefined` as a reply.
![image](https://github.com/saltcorn/large-language-model/assets/65325/5a3f85f4-f325-4e42-bfda-ae3e4b5a804e)

![image](https://github.com/saltcorn/large-language-model/assets/65325/0cc6d2a7-da46-4a19-aa6d-5a3f7e09a33d)
Here it must be 172.17.0.1 since it's the virtual gateway between the 2 containers.

My direct test call (from the saltcorn container) works:
```
root@7ba074ef19d5:/# curl --location --request POST 'http://172.17.0.1:11434/api/generate' --header 'Content-Type: application/json' --data-raw '{
  "model": "benob/vigostral",
  "prompt":"écris un poème haiku",
  "stream": false
 }'

{"model":"benob/vigostral","created_at":"2024-04-15T14:21:02.545540187Z","response":" Dans l'ombre des arbres\n\nLe temps s'écoule sans bruit,\n\nLa nature dort en paix.","done":true,"context":[733,16289,28793,28705,24688,3665,521,1627,8158,3631,23550,733,28748,16289,28793,14527,305,28742,300,2152,634,597,13243,13,13,3514,12974,268,28742,6915,280,291,12062,287,6424,28725,13,13,5798,4735,19187,481,5881,833,28723],"total_duration":536798612,"load_duration":3550333,"prompt_eval_duration":25484000,"eval_count":31,"eval_duration":507195000}root@7ba074ef19d5:/# 
```
The Saltcorn plugin doesn't get the "response".
Any idea?

**Comment by Atozzio** [comment]
Hello @j2l. I have tried the same with "Local Ollama" as my interface backend, and it worked.
<img width="1101" alt="image" src="https://github.com/saltcorn/large-language-model/assets/15627635/e20ca232-664d-4bf1-89b5-0898fcbcbc7b">
<img width="908" alt="image" src="https://github.com/saltcorn/large-language-model/assets/15627635/767402f4-1e65-481f-8ff4-52351274f864">
Mine also failed with "local ollama server" + "OpenAI-compatible API". Would you please give "Local Ollama" a try?

**Comment by j2l** [comment]
Thank you @Atozzio ! I'll have to test it again.
